function BusinessImpact({ impact }) {
  return (
    <section className="analytics-card business-impact-panel" aria-labelledby="impact-title">
      <div className="section-heading"><div><h3 id="impact-title">Business Impact</h3><p>Operational value generated by active automations.</p></div></div>
      <div className="impact-strip">
        {impact.map((item) => <article key={item.label}><strong>{item.value}</strong><span>{item.label}</span></article>)}
      </div>
    </section>
  )
}

export default BusinessImpact
